export * from './game.entity';
export * from './platform.entity';
export * from './esrb-rating.entity';
export * from './publisher.entity';
export * from './screenshot.entity';
export * from './store.entity';
export * from './trailer.entity';
export * from './genre.entity';
export * from './tag.entity';
